# Generated by Django 6.0.2 on 2026-02-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SafeZone",
        ),
        migrations.AddField(
            model_name="cartype",
            name="image_1",
            field=models.CharField(
                blank=True, help_text="data/xe2banh.jpg", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="cartype",
            name="image_2",
            field=models.CharField(
                blank=True, help_text="data/xe4cho.jpeg", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="cartype",
            name="image_3",
            field=models.CharField(
                blank=True, help_text="data/xe8cho.jpg", max_length=100, null=True
            ),
        ),
    ]
