# Generated by Django 6.0.2 on 2026-03-28 12:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0002_delete_safezone_cartype_image_1_cartype_image_2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafeZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("area", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name="cartype",
            name="image_1",
        ),
        migrations.RemoveField(
            model_name="cartype",
            name="image_2",
        ),
        migrations.RemoveField(
            model_name="cartype",
            name="image_3",
        ),
        migrations.AddField(
            model_name="car",
            name="brand_name",
            field=models.CharField(default="Chưa xác định", max_length=100),
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
