# Generated by Django 6.0.2 on 2026-03-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0003_safezone_remove_cartype_image_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="brand_name",
        ),
    ]
