# Generated by Django 6.0.2 on 2026-03-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0005_car_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartype",
            name="brand_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
