# Generated by Django 6.0.2 on 2026-03-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0006_cartype_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
    ]
