# Generated by Django 6.0.2 on 2026-03-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0007_car_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCustom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("IRL_name", models.CharField(max_length=100)),
            ],
        ),
    ]
