# Generated by Django 6.0.2 on 2026-03-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0008_usercustom"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercustom",
            name="role",
            field=models.CharField(default="guest", max_length=10),
        ),
    ]
