# Generated by Django 6.0.2 on 2026-03-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0009_usercustom_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercustom",
            name="book_day",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usercustom",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="usercustom",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
