# Generated by Django 6.0.2 on 2026-04-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0010_usercustom_book_day_usercustom_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercustom",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ xử lý"),
                    ("confirmed", "Đã xác nhận (Chờ nhận xe)"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
