# Generated by Django 6.0.1 on 2026-04-02 13:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_usercustom_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('capacity', models.IntegerField(default=10)),
            ],
        ),
    ]
