# Generated by Django 6.0.1 on 2026-04-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
