# Generated by Django 6.0.1 on 2026-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_cartype_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartype',
            name='is_available',
        ),
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
