# Generated by Django 6.0.1 on 2026-04-03 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_remove_cartype_is_available_car_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_distance', models.FloatField(default=0.0)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='ongoing', max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.car')),
                ('pickup_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='rental.station')),
                ('return_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='rental.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.usercustom')),
            ],
        ),
    ]
