# Generated by Django 6.0.2 on 2026-04-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0015_bookinghistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartype",
            name="brand_name",
        ),
    ]
