# Generated by Django 6.0.2 on 2026-04-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0016_remove_cartype_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
