# Generated by Django 6.0.2 on 2026-04-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0017_car_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="quantity",
        ),
    ]
