# Generated by Django 6.0.2 on 2026-04-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0018_remove_car_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercustom",
            name="pickup_day",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
