# Generated by Django 6.0.2 on 2026-04-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0019_usercustom_pickup_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercustom",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
