# Generated by Django 6.0.2 on 2026-04-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0020_usercustom_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercustom",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
