# Generated by Django 6.0.2 on 2026-04-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0021_usercustom_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="short_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Mô tả ngắn hiển thị trên trang loại xe (admin chỉnh sửa).",
            ),
        ),
    ]
