# Generated by Django 6.0.2 on 2026-04-19 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0022_car_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="detail_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Mô tả chi tiết (HTML từ CKEditor), trang car_description.",
            ),
        ),
        migrations.CreateModel(
            name="CarGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cars/gallery/")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="rental.car",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
