# Generated by Django 6.0.2 on 2026-04-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0024_review_reviewimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Hệ thống thuê xe trực tuyến", max_length=255
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(
                        default="Nền tảng thuê xe nhanh chóng, tiện lợi và đáng tin cậy."
                    ),
                ),
                (
                    "hero_button_text",
                    models.CharField(default="Đặt xe ngay", max_length=100),
                ),
                (
                    "hero_button_url",
                    models.CharField(default="/car-types/", max_length=255),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="homepage/"),
                ),
                (
                    "feature_1_title",
                    models.CharField(default="Nhiều loại xe đa dạng", max_length=255),
                ),
                (
                    "feature_1_description",
                    models.TextField(
                        default="Cung cấp nhiều loại xe phù hợp cho mọi nhu cầu."
                    ),
                ),
                (
                    "feature_2_title",
                    models.CharField(default="Đặt xe nhanh chóng", max_length=255),
                ),
                (
                    "feature_2_description",
                    models.TextField(
                        default="Giao diện đơn giản, dễ sử dụng chỉ trong vài bước."
                    ),
                ),
                (
                    "feature_3_title",
                    models.CharField(default="Thông tin minh bạch", max_length=255),
                ),
                (
                    "feature_3_description",
                    models.TextField(
                        default="Hiển thị đầy đủ thông tin xe và giá thuê rõ ràng."
                    ),
                ),
                (
                    "news_section_title",
                    models.CharField(default="Tin Tức", max_length=255),
                ),
                (
                    "news_section_subtitle",
                    models.CharField(
                        blank=True,
                        default="Các bài viết mới nhất từ hệ thống",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("thumbnail", models.ImageField(upload_to="news/")),
                (
                    "content",
                    models.TextField(help_text="Nội dung bài viết (HTML từ CKEditor)."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
